apiVersion: batch/v1
kind: Job
metadata:
  name: monitor-default-sample
spec:
  template:
    spec:
      containers:
      - name: default-sample
        image: couchbase/server:7.0.2
        command: ["/opt/couchbase/bin/cbdocloader", "-c", "cb-example-ui.default", "-u", "Administrator", "-p", "password", "-b" ,"default", "-m", "100", "-d", "/opt/couchbase/samples/travel-sample.zip"]
      restartPolicy: Never
